repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
- repo: https://github.com/moralrecordings/mrblack
  rev: mrblack-21.12b0
  hooks:
    - id: black
