[tool.pyright]
include = ['mrcrowbar']
typeCheckingMode = 'strict'
reportUnnecessaryIsInstance = false
pythonVersion = '3.7'

[tool.isort]
profile = 'black'
src_paths = 'mrcrowbar'
add_imports = "from __future__ import annotations"
