name: Python tests

on: ["push", "pull_request"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.4.10", "3.5.10", "3.6.13", "3.7.10", "3.8.9", "3.9.4"]
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -e .
                pip install -r requirements.txt
            - name: Run tests
              run: |
                coverage run mrcrowbar/tests.py
            - name: Upload to Coveralls
              uses: coverallsapp/github-action@v1.1.2
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
